/**
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    //先将随机字符串转换为数组并排序 [a, a, b, c, .... , z];
    var tArr = t.split('').sort(), sArr = s.split('').sort();
    var diff = '', idx = 0;
    
    tArr.forEach(function(letter, index) {
        //sArr和tArr按照索引比较字符，即sArr[index]和tArr[index]比较
        if(index === idx) {
            if(sArr[index] !== letter) {
                diff = letter;
            } else {
                idx = index + 1;
            }
        }
    });
    return diff;
};


console.log(findTheDifference('ae', 'aea'));
